[project]
name = "uncertainty-quantification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rich>=14.1.0",
    "tabulate>=0.9.0",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
